name       : ark
version    : 23.04.2
release    : 73
source     :
    - https://cdn.download.kde.org/stable/release-service/23.04.2/src/ark-23.04.2.tar.xz : de386d0a2aec6772fba51a7710e186718c75cecdf589fa3fd8d8dbd203e464ac
homepage   : https://kde.org/applications/utilities/org.kde.ark
license    : GPL-2.0-or-later
component  : desktop.kde.core
summary    : A graphical file compression/decompression utility
description: |
    Ark is a graphical file compression/decompression utility with support for multiple formats, including tar, gzip, bzip2, rar and zip, as well as CD-ROM images.
optimize   : lto
builddeps  :
    - pkgconfig(libarchive)
    - pkgconfig(libunarr)
    - pkgconfig(libzip)
    - bzip2-devel
    - karchive-devel
    - kcrash-devel
    - kdbusaddons-devel
    - kdoctools-devel
    - kiconthemes-devel
    - kitemmodels-devel
    - kparts-devel
    - kpty-devel
rundeps    :
    - unrar
setup      : |
    %cmake_ninja -DBUILD_TESTING=OFF
build      : |
    %ninja_build
install    : |
    %ninja_install

    # remove docs
    rm -rf $installdir/usr/share/doc
