name       : ark
version    : 19.04.3
release    : 26
source     :
    - https://cdn.download.kde.org/stable/applications/19.04.3/src/ark-19.04.3.tar.xz : a06cc2937aa4ed41bab0a38344164f367b993a80bcd74011e4ab72643bfee8ee
license    : GPL-2.0-or-later
component  : desktop.kde.core
optimize   : lto
summary    : A graphical file compression/decompression utility
description: |
    Ark is a graphical file compression/decompression utility with support for multiple formats, including tar, gzip, bzip2, rar and zip, as well as CD-ROM images.
builddeps  :
    - pkgconfig(libarchive)
    - pkgconfig(libunarr)
    - pkgconfig(libzip)
    - pkgconfig(lrzip)
    - pkgconfig(Qt5Core)
    - bzip2-devel
    - extra-cmake-modules
    - karchive-devel
    - kconfig-devel
    - kcrash-devel
    - kdbusaddons-devel
    - kdoctools-devel
    - ki18n-devel
    - kiconthemes-devel
    - kio-devel
    - kitemmodels-devel
    - kparts-devel
    - kpty-devel
    - kservice-devel
    - kwidgetsaddons-devel
    - shared-mime-info
setup      : |
    %cmake_ninja -DBUILD_TESTING=OFF
build      : |
    %ninja_build
install    : |
    %ninja_install
