name       : ark
version    : 17.04.3
release    : 3
source     :
    - https://download.kde.org/stable/applications/17.04.3/src/ark-17.04.3.tar.xz : 36ea400aa72ee3e8ec09c3ef2a0ffc5dad6b4afb34aa0c0736a885f4635333ad
license    :
    - GPL-2.0
    - LGPL-3.0
component  : desktop.kde.core
summary    : A graphical file compression/decompression utility
description: |
    Ark is a graphical file compression/decompression utility with support for multiple formats, including tar, gzip, bzip2, rar and zip, as well as CD-ROM images.
builddeps  :
    - pkgconfig(gl)
    - pkgconfig(libarchive)
    - pkgconfig(libzip)
    - pkgconfig(Qt5Core)
    - bzip2-devel
    - extra-cmake-modules
    - karchive-devel
    - kconfig-devel
    - kcrash-devel
    - kdbusaddons-devel
    - kdoctools-devel
    - ki18n-devel
    - kiconthemes-devel
    - kio-devel
    - kitemmodels-devel
    - kparts-devel
    - kpty-devel
    - kservice-devel
    - kwidgetsaddons-devel
    - shared-mime-info
setup      : |
    %cmake .
build      : |
    %make
install    : |
    %make_install
