name       : ark
version    : 18.12.1
release    : 20
source     :
    - https://cdn.download.kde.org/stable/applications/18.12.1/src/ark-18.12.1.tar.xz : 0665a10b860a914b64b5e41de6c159f5dac9fbf1dce10f5c097cc88611568add
license    : GPL-2.0-or-later
component  : desktop.kde.core
optimize   : lto
summary    : A graphical file compression/decompression utility
description: |
    Ark is a graphical file compression/decompression utility with support for multiple formats, including tar, gzip, bzip2, rar and zip, as well as CD-ROM images.
builddeps  :
    - pkgconfig(libarchive)
    - pkgconfig(libzip)
    - pkgconfig(Qt5Core)
    - bzip2-devel
    - extra-cmake-modules
    - karchive-devel
    - kconfig-devel
    - kcrash-devel
    - kdbusaddons-devel
    - kdoctools-devel
    - ki18n-devel
    - kiconthemes-devel
    - kio-devel
    - kitemmodels-devel
    - kparts-devel
    - kpty-devel
    - kservice-devel
    - kwidgetsaddons-devel
    - shared-mime-info
setup      : |
    %cmake_ninja -DBUILD_TESTING=OFF
build      : |
    %ninja_build
install    : |
    %ninja_install
