name       : ark
version    : 18.12.2
release    : 21
source     :
    - https://cdn.download.kde.org/stable/applications/18.12.2/src/ark-18.12.2.tar.xz : cbeb31893611fe52181a78761acd4e862e4ad0dd007d03ce9e78993ef143f62b
license    : GPL-2.0-or-later
component  : desktop.kde.core
optimize   : lto
summary    : A graphical file compression/decompression utility
description: |
    Ark is a graphical file compression/decompression utility with support for multiple formats, including tar, gzip, bzip2, rar and zip, as well as CD-ROM images.
builddeps  :
    - pkgconfig(libarchive)
    - pkgconfig(libzip)
    - pkgconfig(Qt5Core)
    - bzip2-devel
    - extra-cmake-modules
    - karchive-devel
    - kconfig-devel
    - kcrash-devel
    - kdbusaddons-devel
    - kdoctools-devel
    - ki18n-devel
    - kiconthemes-devel
    - kio-devel
    - kitemmodels-devel
    - kparts-devel
    - kpty-devel
    - kservice-devel
    - kwidgetsaddons-devel
    - shared-mime-info
setup      : |
    %cmake_ninja -DBUILD_TESTING=OFF
build      : |
    %ninja_build
install    : |
    %ninja_install
