name       : ark
version    : 18.04.3
release    : 14
source     :
    - https://cdn.download.kde.org/stable/applications/18.04.3/src/ark-18.04.3.tar.xz : e5cc2484dbd422b28b17b23e0563d392746b7e89d69edac3c2a2468d760dbb09
license    :
    - GPL-2.0
    - LGPL-3.0
component  : desktop.kde.core
optimize   : lto
summary    : A graphical file compression/decompression utility
description: |
    Ark is a graphical file compression/decompression utility with support for multiple formats, including tar, gzip, bzip2, rar and zip, as well as CD-ROM images.
builddeps  :
    - pkgconfig(gl)
    - pkgconfig(libarchive)
    - pkgconfig(libzip)
    - pkgconfig(Qt5Core)
    - bzip2-devel
    - extra-cmake-modules
    - karchive-devel
    - kconfig-devel
    - kcrash-devel
    - kdbusaddons-devel
    - kdoctools-devel
    - ki18n-devel
    - kiconthemes-devel
    - kio-devel
    - kitemmodels-devel
    - kparts-devel
    - kpty-devel
    - kservice-devel
    - kwidgetsaddons-devel
    - shared-mime-info
setup      : |
    %cmake_ninja -DBUILD_TESTING=OFF
build      : |
    %ninja_build
install    : |
    %ninja_install
