name       : ark
version    : 17.08.1
release    : 4
source     :
    - https://download.kde.org/stable/applications/17.08.1/src/ark-17.08.1.tar.xz : c9c49e220adf12d8132a2e307f34e28ffbd317e41a64823e2f901ac24ef92f05
license    :
    - GPL-2.0
    - LGPL-3.0
component  : desktop.kde.core
summary    : A graphical file compression/decompression utility
description: |
    Ark is a graphical file compression/decompression utility with support for multiple formats, including tar, gzip, bzip2, rar and zip, as well as CD-ROM images.
builddeps  :
    - pkgconfig(gl)
    - pkgconfig(libarchive)
    - pkgconfig(libzip)
    - pkgconfig(Qt5Core)
    - bzip2-devel
    - extra-cmake-modules
    - karchive-devel
    - kconfig-devel
    - kcrash-devel
    - kdbusaddons-devel
    - kdoctools-devel
    - ki18n-devel
    - kiconthemes-devel
    - kio-devel
    - kitemmodels-devel
    - kparts-devel
    - kpty-devel
    - kservice-devel
    - kwidgetsaddons-devel
    - shared-mime-info
setup      : |
    %cmake .
build      : |
    %make
install    : |
    %make_install
