name       : ark
version    : 21.08.0
release    : 57
source     :
    - https://cdn.download.kde.org/stable/release-service/21.08.0/src/ark-21.08.0.tar.xz : dd7daf89f1821edcb03bbe41344f85198f5709135a8d4d273fe7ba611230f522
homepage   : https://kde.org/applications/utilities/org.kde.ark
license    : GPL-2.0-or-later
component  : desktop.kde.core
summary    : A graphical file compression/decompression utility
description: |
    Ark is a graphical file compression/decompression utility with support for multiple formats, including tar, gzip, bzip2, rar and zip, as well as CD-ROM images.
optimize   : lto
builddeps  :
    - pkgconfig(libarchive)
    - pkgconfig(libunarr)
    - pkgconfig(libzip)
    - pkgconfig(lrzip)
    - bzip2-devel
    - karchive-devel
    - kcrash-devel
    - kdbusaddons-devel
    - kdoctools-devel
    - kitemmodels-devel
    - kparts-devel
    - kpty-devel
setup      : |
    %cmake_ninja -DBUILD_TESTING=OFF
build      : |
    %ninja_build
install    : |
    %ninja_install

    # remove docs
    rm -rf $installdir/usr/share/doc
